name: Wyoming Cloud Streamer
slug: wyoming_cloud_streamer
version: "0.0.1"
description: Wyoming server for cloud TTS providers (streaming)
arch: [amd64, aarch64, armv7, armhf, i386]
init: false
startup: application
boot: auto
ingress: false
host_network: false
ports:
  "10200/tcp": 10200
map:
  - config:rw

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

schema:
  gcp_credentials_path: str?
  openai_model: str? 
  openai_api_key: password?

options:
  gcp_credentials_path: "/config/SERVICE_ACCOUNT.json"
  openai_model: "gpt-4o-mini-tts"
  openai_api_key: ""
